### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by plandolt**
5.5 is not available anymore.

### CODE REVIEW

**Comment by dominikzogg** [comment]
@scuben if the version on the ppa was dropped we should also remove https://github.com/vagrant-php/ubuntu/tree/14.04/ansible/roles/php55 and https://github.com/vagrant-php/ubuntu/blob/14.04/ansible/playbook.yml#L35

**Comment by plandolt** [comment]
@dominikzogg this is true. I'm gonna do that when I find some free time.

**Comment by dominikzogg** [comment]
https://github.com/vagrant-php/ubuntu/commit/5f5f0f2c936bfa5aee5fda1de3ba88e4536b5720

**Comment by plandolt** [comment]
Thank you to complete the PR @dominikzogg

**Comment by dominikzogg** [comment]
@scuben you're welcome

**Pull request closed without merging**
