### PR TITLE
system user config

### PR DESCRIPTION
**Pull request by plandolt**
Implementation for #17

### CODE REVIEW

**Comment by dominikzogg** [comment]
@scuben this is an alternative solutions to vagrant-user.yml, which means we should deprecated my solution and add some documentation

edit: bad idea to deprecated, cause there can be project specific user overrides

**Comment by plandolt** [comment]
@dominikzogg I would not deprecate the other way. I see this as a new feature for global-user-specific settings in additional to project-user-specific settings.

**Comment by dominikzogg** [comment]
@scuben k

i would suggest the following:
- vagrant-default.yml
- vagrant-user-default.yml (your input)
- vagrant.yml
- vagrant-user.yml

**Comment by dominikzogg** [comment]
https://github.com/vagrant-php/ubuntu/commit/bd59ec91b61fcc0a996de3b4740a1b66333221c7

**Comment by dominikzogg** [comment]
@scuben #17 resolves the task, it would be cool if you could close this PR as well.

**Pull request closed without merging**
