### PR TITLE
add prototype for multihost support

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by dominikzogg** [comment]
@scuben what do you think about this multihost support implementation?

It works fine, except the mount binds

**Comment by dominikzogg** [comment]
ok, bindmount sollte nun auch klappen

**Comment by dominikzogg** [comment]
ok, bindmount should run

**Comment by dominikzogg** [comment]
what its not supported is to have multiple application types within same box

**Comment by dominikzogg** [comment]
@maximkott what do you think about the multihost-support implementation (for those who prefere shared boxes)?

**Comment by dominikzogg** [comment]
@scuben what do you think about this PR?

**Comment by plandolt** [comment]
@dominikzogg I did only have a look at the code, but that looks good. To be honest I don't think this will be used a lot. But it should be extended that one is able to configure different applications for each subhostname. Another big addition that makes this better usable to allow an easy extension point to add "custom-applications" by easily add a custom application.conf for a custom project.

**Comment by dominikzogg** [comment]
@scuben thank you for your feedback.

Allow multiple application types means, that multiple nginx and php roles needed at ones, first is easy to solve, second means, that for example aliases needed to be prefixed sf => sf2 for example.

How would you solve custom applications? User provided own roles?

**Comment by dominikzogg** [comment]
@scuben this is an early version of multiapplication support: https://github.com/vagrant-php/ubuntu/pull/15, but without custom project support

**Pull request merged**
